### PR TITLE
Added Cloudflare troubleshooting information

### PR DESCRIPTION
**Pull request by eqxDev**
Was having issues once moving to a production env with Rocket Loader & HTML minification conflicting causing Livewire to randomly fail.

### CODE REVIEW

**Comment by calebporzio** [comment]
Thanks!

**Comment by eqxDev** [comment]
> Thanks!

No worries, might be an idea to chuck this on the livewire v3 documentation too, I was unable to find a git repo for it.

**Comment by joshhanley** [comment]
@eqxDev V3 docs are now in the main Livewire repo, if you don't mind PR it there too 🙂

**Comment by calebporzio** [comment]
Thanks, Josh alerted me that the contents of this PR are more V3 relevant (the error message and the reference to wire:navigate, so yeah please PR there!)

**Pull request merged**
