### PR TITLE
Fixed typo in alpine-js

### PR DESCRIPTION
**Pull request by calpayne**

### CODE REVIEW

**Review by theriddleofenigma — CHANGES_REQUESTED** [review]
when a user clicks the first button a property called `$foo` is set to `bar`, and when a user clicks the second button, `$foo` is set to `baz`.

We can mention the buttons as the first button and the second button in here. Since that example contains only 2 buttons.

**Comment by theriddleofenigma** [comment]
> when a user clicks the first button a property called `$foo` is set to `bar`, and when a user clicks the second button, `$foo` is set to `baz`.
> 
> We can mention the buttons as the first button and the second button in here. Since that example contains only 2 buttons.

@calpayne Thanks for considering my comment and changing it accordingly. Have a great day :)

**Comment by calpayne** [comment]
> > when a user clicks the first button a property called `$foo` is set to `bar`, and when a user clicks the second button, `$foo` is set to `baz`.
> > We can mention the buttons as the first button and the second button in here. Since that example contains only 2 buttons.
> 
> @calpayne Thanks for considering my comment and changing it accordingly. Have a great day :)

Thanks for making the suggestion, have a good day 👍

**Comment by calebporzio** [comment]
Thanks!

**Pull request merged**
